// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Prefix        string             `json:"prefix"`
	PublicID      string             `json:"public_id"`
	Scope         []string           `json:"scope"`
	EncryptionIv  string             `json:"encryption_iv"`
	EncryptedText string             `json:"encrypted_text"`
	Algorithm     string             `json:"algorithm"`
	Rotations     int32              `json:"rotations"`
	SetupID       pgtype.UUID        `json:"setup_id"`
	LastRotatedAt pgtype.Timestamptz `json:"last_rotated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DestroyAt   pgtype.Timestamptz `json:"destroy_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectEnvironment struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	ProjectEnvironmentID pgtype.UUID        `json:"project_environment_id"`
	RoleID               pgtype.UUID        `json:"role_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ProjectRole struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Permissions []byte             `json:"permissions"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Setup struct {
	ID              pgtype.UUID        `json:"id"`
	IsSetupComplete bool               `json:"is_setup_complete"`
	DestroyAt       pgtype.Timestamptz `json:"destroy_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SetupOwner struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	SetupID   pgtype.UUID        `json:"setup_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	IsEmailVerified bool               `json:"is_email_verified"`
	IsSuspended     bool               `json:"is_suspended"`
	IsInactive      bool               `json:"is_inactive"`
	IsDeleted       bool               `json:"is_deleted"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserAuthMethod struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserAuthSession struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	AccessVersion  int32              `json:"access_version"`
	RefreshVersion int32              `json:"refresh_version"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	IDAddress      string             `json:"id_address"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	SetupID   pgtype.UUID        `json:"setup_id"`
	IsActive  bool               `json:"is_active"`
	IsDeleted bool               `json:"is_deleted"`
	DestroyAt pgtype.Timestamptz `json:"destroy_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceRole struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Permissions []byte             `json:"permissions"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
